FLAGS	 = -w -g -std=c++11

renderer:
	g++ jnf_renderer.cpp sampler.cpp BBox.cpp RGBColor.cpp GeometricObject.cpp ShadeRec.cpp Utilities.cpp World.cpp Display.cpp Light.cpp Material.cpp BRDF.cpp camera.cpp $(FLAGS) -o $@
